name: Build Libraries for All Platforms

# Trigger the workflow on pushes or pull requests to the main branch
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

# Define the jobs for each platform
jobs:
  # Windows build job
  build-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Install CMake
        run: choco install cmake

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew
        shell: bash

      - name: Build with Gradle
        run: ./gradlew copyLibs_static_windows_x64 copyLibs_static_windows_arm64 copyLibs_shared_windows_x64 copyLibs_shared_windows_arm64

      - name: Upload Windows static libraries
        uses: actions/upload-artifact@v4
        with:
          name: windows-static-libs
          path: build/libs/static/windows

      - name: Upload Windows shared libraries (DLLs)
        uses: actions/upload-artifact@v4
        with:
          name: windows-shared-libs
          path: build/libs/shared/windows

  # Mac and iOS build job
  build-mac:
    runs-on: macos-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Select Xcode version
        run: sudo xcode-select -s /Applications/Xcode.app

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew

      - name: Build with Gradle
        run: ./gradlew copyLibs_static_mac_x64 copyLibs_static_mac_arm64 copyLibs_shared_mac_x64 copyLibs_shared_mac_arm64 copyLibs_static_ios_arm64 copyLibs_static_ios_x64 copyLibs_shared_ios_arm64 copyLibs_shared_ios_x64

      - name: Upload Mac static libraries
        uses: actions/upload-artifact@v4
        with:
          name: mac-static-libs
          path: build/libs/static/mac

      - name: Upload Mac shared libraries
        uses: actions/upload-artifact@v4
        with:
          name: mac-shared-libs
          path: build/libs/shared/mac

      - name: Upload iOS static libraries
        uses: actions/upload-artifact@v4
        with:
          name: ios-static-libs
          path: build/libs/static/ios

      - name: Upload iOS shared libraries
        uses: actions/upload-artifact@v4
        with:
          name: ios-shared-libs
          path: build/libs/shared/ios

  # Linux build job
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential cmake python3

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew

      - name: Build with Gradle
        run: ./gradlew copyLibs_static_linux_x64 copyLibs_static_linux_arm64 copyLibs_shared_linux_x64 copyLibs_shared_linux_arm64

      - name: Upload Linux static libraries
        uses: actions/upload-artifact@v4
        with:
          name: linux-static-libs
          path: build/libs/static/linux

      - name: Upload Linux shared libraries
        uses: actions/upload-artifact@v4
        with:
          name: linux-shared-libs
          path: build/libs/shared/linux

  # Android build job
  build-android:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Set up Android SDK
        uses: android-actions/setup-android@v3
        with:
          cmdline-tools-version: '9477386'

      - name: Install NDK
        run: |
          sdkmanager "ndk;26.1.10909125"

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew

      - name: Build with Gradle
        run: ./gradlew copyLibs_static_android_arm64 copyLibs_static_android_armv7 copyLibs_static_android_x64 copyLibs_static_android_x86 copyLibs_shared_android_arm64 copyLibs_shared_android_armv7 copyLibs_shared_android_x64 copyLibs_shared_android_x86
        env:
          ANDROID_NDK_HOME: $ANDROID_HOME/ndk/26.1.10909125

      - name: Upload Android static libraries
        uses: actions/upload-artifact@v4
        with:
          name: android-static-libs
          path: build/libs/static/android

      - name: Upload Android shared libraries
        uses: actions/upload-artifact@v4
        with:
          name: android-shared-libs
          path: build/libs/shared/android

  # Emscripten build job
  build-emscripten:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Set up Emscripten
        uses: mymindstorm/setup-emsdk@v14
        with:
          version: 'latest'

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew

      - name: Build with Gradle
        run: ./gradlew copyLibs_static_emscripten_wasm copyLibs_shared_emscripten_wasm
        env:
          EMSDK: /usr/lib/emsdk

      - name: Upload Emscripten static libraries
        uses: actions/upload-artifact@v4
        with:
          name: emscripten-static-libs
          path: build/libs/static/emscripten

      - name: Upload Emscripten shared libraries
        uses: actions/upload-artifact@v4
        with:
          name: emscripten-shared-libs
          path: build/libs/shared/emscripten